name:  ✏️ README Repos List

on:
  push:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Run readme-repos-list
        uses: DenverCoderOne/readme-repos-list@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "user:forks-by-kieran fork:only"
          max: 100
          sort: "updated"
          path: pages/FORKS.md