# This workflow builds a list of your starred repositories
name: ⭐ Pull Stars

on:
  push:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Generate the list
      - name: Create star list
        uses: rverst/stargazer@v1.2.6
        with:
          github-user: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          list-file: "pages/STARRED-REPOS.md"

      # Commit the changes
      - name: Commit files
        run: |
          git config --local user.email "actions@noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "⭐ Updated Stars"

      # Push the changes
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
